### ISSUE TITLE
BigFloat support

### ISSUE THREAD

**Issue by dlfivefifty** [andreasnoack/ToeplitzMatrices.jl#6]
Right now BigFloats are currently not supported, because plan_fft doesn't return a Base.DFT.Plan type, and doesn't support the right syntax, see

https://github.com/JuliaLang/julia/issues/15348

Maybe the dft and idft plans should be templated out to work around this?  I can do this on my fork.

**Comment by dlfivefifty** [comment]
One option is to separate the plans from the data structure.  So instead of, for example, the current TriangularToeplitz there would be two types:

```julia
type TriangularToeplitz{T<:Number} <: AbstractToeplitz{T}
    ve::Vector{T}
    uplo::Char
end

type PlannedToeplitz{TT<:AbstractToeplitz,T<:Number} <: AbstractToeplitz{T}
    matrix::TT  # represents the toeplitz matrix being planned
    vc_dft::Vector{Complex{T}}
    tmp::Vector{Complex{T}}
    dft::Base.DFT.Plan
    idft::Base.DFT.Plan
end
```

**Comment by andreasnoack** [comment]
Has `fft` ever worked with `BigFloat`s in Julia? You are requesting that it would still be possible to construct `BigFloat` Toeplitz matrices even though the FFT is not working, right? That seems reasonable.

I thought about something similar to `PlannedToeplitz`, and it would make sense to think of it as a factorization similarly to how we factorize dense matrices before a solve. Here it is just mainly before multiplication. I like the idea, but I need to think a little about it before changing the structure.

**Comment by dlfivefifty** [comment]
fft works for BigFloats already in 0.4.   rfft does not.  I’m going to write a fast Toeplitz multiply for BigFloat’s by overloading *, and calling fft instead of rfft.

**Comment by dlfivefifty** [comment]
Hmm, looks like I’m going crazy: fft is no longer working with BigFloat for me.

**Comment by dlfivefifty** [comment]
Sorry for the confusion: it turns out the plan_fft(::BigFloat) was overloaded in ApproxFun.  It shouldn’t be overloading Base.plan_fft, so I’ll fix that.   @MikaelSlevinsky

**Comment by MikaelSlevinsky** [comment]
I originally wrote the BigFloat fft for fast Toeplitz matrix-vector multiply in SincFun.jl (sinc differentiation matrices are Toeplitz) ... funny that's it's come "full circle" to ToeplitzMatrices.jl!

**Comment by dlfivefifty** [comment]
I have BigFloat fast transforms working now in my fork.  The good thing is it requires almost no changes to ToeplitzMatrices.jl (other than removing a few <: BlasFloat restrictions).

**Comment by andreasnoack** [comment]
Please open a PR when you consider it ready. It would be a great addition.
