### ISSUE TITLE
Add to METADATA

### ISSUE THREAD

**Issue by dlfivefifty** [andreasnoack/ToeplitzMatrices.jl#8]
I'd like to require this package in FastTransforms.jl, but it's not currently in METADATA.

**Comment by andreasnoack** [comment]
I'll try to submit a PR. In theory, I'm supposed to provide a documentation before doing that and I have a bit of other stuff on my plate right now.

**Comment by dlfivefifty** [comment]
I'll have a go adding documentation

**Comment by andreasnoack** [comment]
Awesome. Thanks. See https://github.com/JuliaLang/METADATA.jl/pull/5015

**Comment by dlfivefifty** [comment]
Thanks!
